AllCops:
  DisplayCopNames: true
  Exclude:
    - 'bin/**/*'
    - 'config/initializers/devise.rb'
    - 'db/**/*'
Metrics/LineLength:
  Max: 120

Style/ClassAndModuleChildren:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false